name: Docs
on:
  push:
    branches:
      - master
  label:
    types:
      - created

jobs:
  docs:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: README.md → Home.md
        run: mv docs/README.md docs/Home.md

      - name: Docs → Wiki
        uses: SwiftDocOrg/github-wiki-publish-action@v1
        with:
          path: "docs"
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
