version: '3.9'
services:
  reverse-proxy:
    image: traefik:v2.7
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./traefik:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock
  uk-axvr-redirect:
    build:
      context: .
    depends_on:
      - reverse-proxy
    labels:
      traefik.enable: 'true'
