name: CI
on: [push, pull_request]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install Clj-kondo
        uses: DeLaGuardo/setup-clj-kondo@afc83dbbf4e7e32e04649e29dbf30668d30e9e3e
        with:
          version: '2022.02.09'

      - name: Run clj-kondo
        run: clj-kondo --lint src

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install Clojure
        uses: DeLaGuardo/setup-clojure@4.0
        with:
          cli: '1.10.3.1082'

      - name: Run tests
        run: clojure -X:test
