name: Update packages
on:
  workflow_dispatch:
  schedule:
    - cron: '17 8,17 * * *'

jobs:
  run:
    name: Update spec files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Update spec files
        run: ./update.sh

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: Update package versions
          add: '*'
